import { pino } from "pino"

export const logger = pino(
  {
    level: process.env.LOG_LEVEL || "debug",
    redact: {
      paths: [
        "password",
        "passwordHash",
        "token",
        "accessToken",
        "refreshToken",
        "access_token",
        "refresh_token",
        "authorization",
        "*.password",
        "*.passwordHash",
        "*.token",
        "*.accessToken",
        "*.refreshToken",
        "*.access_token",
        "*.refresh_token",
        "*.authorization",
        "*.*.password",
        "*.*.passwordHash",
        "*.*.token",
        "*.*.accessToken",
        "*.*.refreshToken",
        "*.*.access_token",
        "*.*.refresh_token",
        "req.body.password",
        "req.body.passwordHash",
        "req.body.token",
        "req.body.accessToken",
        "req.body.refreshToken",
        "req.body.access_token",
        "req.body.refresh_token",
        "req.headers.authorization",
        "req.headers.cookie",
        "res.headers['set-cookie']",
      ],
      censor: "[REDACTED]",
    },
  },
  process.stdout
)
